name: Build & Deploy Docker Image - 1

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types:
      - closed
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - dev
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${GITHUB_REF}
        
  build-and-deploy-to-dev:
    if: github.ref == 'refs/heads/dev'
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Approve DEV deployment
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: lakshanyap-test
          minimum-approvals: 1
          issue-title: "Deploy docker image to DEV?"
          issue-body: "Please approve or deny the deployment docker image to DEV"

      - name: Build Docker image - DEV
        if: github.ref == 'refs/heads/dev'
        run: |
          echo Building Docker Image for DEV environment      

  build-and-deploy-to-stg:
    if: github.ref == 'refs/heads/main' && github.event.pull_request.merged == true
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: build-and-deploy-to-dev
    steps:
      - name: Approve STG deployment
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: lakshanyap-test
          minimum-approvals: 1
          issue-title: "Deploy docker image to STG?"
          issue-body: "Please approve or deny the deployment docker image to STG"
          
      - name: Build Docker image - STG
        run: |
          echo Building Docker Image for STG environment
