
name: Build & Deploy Docker Image - 1

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      rules_version_env:
        description: 'Rules Version. This decides the environment to deploy the rules.'
        required: true
        default: 'dev'
        type: choice
        options:  # The options should be the same as the different non-prod subdirectories in the rules directory
          - 'dev'
          - 'stg'
          - 'int'
          - 'uat'
          - 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${GITHUB_REF}
        
  build-and-deploy-non-prod:
    if: ${{ inputs.rules_version_env == 'dev' || inputs.rules_version_env == 'stg' || inputs.rules_version_env == 'int' || inputs.rules_version_env == 'uat' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build and Deploy - Non Prod
        run: echo "build and deploy to non prod"   

  build-and-deploy-prod:
    if: ${{ inputs.rules_version_env == 'main' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build and Deploy - Non Prod
        run: echo "build and deploy to non prod"   
  
  check-pod-status:
    runs-on: ubuntu-latest
    needs: [build-and-deploy-non-prod, build-and-deploy-prod]
    steps:
      - name: Check pod status
        run: echo "check pod status"
